# fly.toml app configuration file generated for novacasa-server on 2023-05-30T16:01:34-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "novacasa-server"
primary_region = "mia"

[env]
  PORT = "8080"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
